# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Cliente: ')),
                ('email', models.CharField(max_length=30, verbose_name='Email: ')),
                ('situacao', models.CharField(choices=[('Autor', 'Autor'), ('Reu', 'Reu'), ('Advogado do Autor', 'Advogado do Autor'), ('advogado_Reu', 'Advogado do Reu')], max_length=20, verbose_name='Situa\xe7\xe3o do Cliente: ')),
                ('cpf_cpnj', models.CharField(max_length=30, unique=True, verbose_name='CPF ou CNPJ: ')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro: ')),
                ('numero', models.CharField(max_length=6, verbose_name='Numero: ')),
                ('complemento', models.CharField(max_length=20, verbose_name='Complemento: ')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP: ')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro: ')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade: ')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapa'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Cear\xe1'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranh\xe3o'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Para'), ('PB', 'Paraiba'), ('PR', 'Parana'), ('PE', 'Pernambuco'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RR', 'Roraima'), ('RO', 'Rondonia'), ('SC', 'Santa Catarina'), ('SP', 'Sao Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=20, verbose_name='Estado: ')),
                ('valor_desconto', models.CharField(choices=[('5', '5%'), ('10', '10%'), ('15', '15%'), ('20', '20%'), ('25', '25%'), ('30', '30%'), ('35', '35%'), ('40', '30%'), ('45', '45%'), ('50', '40%'), ('55', '55%'), ('60', '60%'), ('65', '65%'), ('70', '60%'), ('75', '75%'), ('80', '80%'), ('85', '85%'), ('90', '90%'), ('95', '95%'), ('100', '100%')], max_length=5, verbose_name='Receber\xe1 de desconto: ')),
                ('observacao_texto', models.TextField(verbose_name='Observa\xe7\xf5es sobre sobre o cliente: ')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('numero_processo', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('status_processo', models.CharField(choices=[('Em Espera', 'Em Espera'), ('Em trabalho', 'Em trabalho'), ('Em faturamento', 'Em faturamento'), ('Faturado', 'Faturado')], max_length=20, verbose_name='Status do Processo: ')),
                ('situacao_processo', models.CharField(choices=[('1 instancia', '1 instancia'), ('2 instancia', '2 instancia'), ('3 instancia', '3 instancia'), ('Execu\xe7\xe3o', 'Execu\xe7\xe3o')], max_length=20, verbose_name='Status do Processo: ')),
                ('cidade', models.CharField(max_length=30, verbose_name='Cidade: ')),
                ('vara', models.CharField(max_length=3, verbose_name='Vara: ')),
                ('nome_autor', models.CharField(max_length=100, verbose_name='Nome do Autor: ')),
                ('nome_reu', models.CharField(max_length=100, verbose_name='Nome do Reu: ')),
                ('nome_adv_autor', models.CharField(max_length=100, verbose_name='Nome do Advogado do Autor: ')),
                ('nome_adv_reu', models.CharField(max_length=100, verbose_name='Nome do Advogado do Reu: ')),
                ('data_entrada', models.DateTimeField(verbose_name='Data de Entrada: ')),
                ('prazo_final', models.DateTimeField(verbose_name='Prazo Final: ')),
                ('data_saida', models.DateTimeField(verbose_name='Data de Saida: ')),
                ('servicos_escolhas', multiselectfield.db.fields.MultiSelectField(choices=[('Calculos Trabalhistas', 'Calculos Trabalhistas'), ('Assistencia Tecnica em Pericia', 'Assistencia Tecnica em Pericia'), ('Engenharia de Seguran\xe7a de Trabalho', 'Engenharia de Seguran\xe7a de Trabalho'), ('Auditoria Trabalhista', 'Auditoria Trabalhista')], max_length=4, verbose_name='Servi\xe7os a serem escolhidos: ')),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Cadastro')),
            ],
        ),
    ]
