# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabalhos_executados', multiselectfield.db.fields.MultiSelectField(choices=[('Imp. Calculo', 'Imp. Calculo'), ('Imp. Laudo', 'Imp. Laudo'), ('Atual. Valores', 'Atual. Valores'), ('Laudo para Inicial', 'Laudo para Inicial'), ('Apresenta\xe7\xe3o de calculos', 'Apresenta\xe7\xe3o de calculos'), ('Impugna\xe7\xe3o /. Embargos', 'Impugna\xe7\xe3o /. Embargos'), ('Calculo Contigencia', 'Calculo Contigencia'), ('Perito do Juizo', 'Perito do Juizo'), ('Quesitos', 'Quesitos')], max_length=150, verbose_name='Tipo Salario')),
                ('justica', multiselectfield.db.fields.MultiSelectField(choices=[('Civel', 'Civel'), ('Trabalhista', 'Trabalhista'), ('Civel Fed.', 'Civel Fed.')], max_length=28, verbose_name='Justi\xe7a')),
                ('tipo_pagamento', multiselectfield.db.fields.MultiSelectField(choices=[('A vista / Na entrega', 'A vista / Na entrega'), ('Faturado', 'Faturado')], max_length=29, verbose_name='Tipo Salario')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Data de vencimento')),
            ],
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicos_escolhas', multiselectfield.db.fields.MultiSelectField(choices=[('Por Mes e por demanda', 'Por Mes e por demanda'), ('Por Mes e por pre\xe7o fixo', 'Por Mes e por pre\xe7o fixo'), ('Por demanda', 'Por demanda')], max_length=58, verbose_name='Servi\xe7os a serem escolhidos')),
                ('tipo_fatura', multiselectfield.db.fields.MultiSelectField(choices=[('Por Mes e por demanda', 'Por Mes e por demanda'), ('Por Mes e por pre\xe7o fixo', 'Por Mes e por pre\xe7o fixo'), ('Por demanda', 'Por demanda')], max_length=58, verbose_name='Tipo de fatura')),
                ('numero_processo', models.CharField(max_length=100, verbose_name='Numero do processo')),
                ('nome_autor', models.CharField(max_length=100, verbose_name='Nome do autor')),
                ('numero_autores', models.IntegerField(verbose_name='Numero de autores')),
                ('valor', models.FloatField(verbose_name='Valor a cobrar')),
                ('data_entrega', models.DateField(verbose_name='Data de vencimento')),
                ('codigo_calculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Calculo')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_admissao', models.DateField(verbose_name='Data de Admiss\xe3o')),
                ('data_demissao', models.DateField(verbose_name='Data de Demiss\xe3o')),
                ('data_distribuido', models.DateField(verbose_name='Data em que o processo saiu da vara trabalhista (distribuido)')),
                ('tipo_salario', multiselectfield.db.fields.MultiSelectField(choices=[('Hora', 'Hora'), ('\u1e3ees', 'Mes')], max_length=8, verbose_name='Tipo Salario')),
                ('tipo_demissao', multiselectfield.db.fields.MultiSelectField(choices=[('Sem Justa causa', 'Sem Justa causa'), ('Justa', 'Justa')], max_length=21, verbose_name='Tipo Demissao')),
                ('status_processo', models.CharField(choices=[('Em Espera', 'Em Espera'), ('Em trabalho', 'Em trabalho'), ('Em faturamento', 'Em faturamento'), ('Faturado', 'Faturado')], max_length=20, verbose_name='Status do Processo')),
                ('principal_atualizado', models.CharField(max_length=30, verbose_name='Principal Atualizado')),
                ('juros_mora', models.CharField(max_length=30, verbose_name=' Juros de Mora')),
                ('total_bruto', models.CharField(max_length=30, verbose_name='Total Bruto')),
                ('inss_autor', models.CharField(max_length=30, verbose_name='INSS Autor')),
                ('irrf', models.CharField(max_length=30, verbose_name='I.R.R.F')),
                ('informacoes_calculo', models.TextField(verbose_name='Dados e informa\xe7\xf5es para calculo')),
            ],
        ),
        migrations.RenameModel(
            old_name='Cadastro',
            new_name='Cliente',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='servicos_escolhas',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='status_processo',
        ),
        migrations.AddField(
            model_name='servico',
            name='codigo_processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Processo'),
        ),
        migrations.AddField(
            model_name='calculo',
            name='codigo_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Servico'),
        ),
    ]
