# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='data_entrada',
            field=models.DateField(verbose_name='Data de Entrada: '),
        ),
        migrations.AlterField(
            model_name='processo',
            name='data_saida',
            field=models.DateField(verbose_name='Data de Saida: '),
        ),
        migrations.AlterField(
            model_name='processo',
            name='prazo_final',
            field=models.DateField(verbose_name='Prazo Final: '),
        ),
    ]
