# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 19:35
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20171014_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='servicos_escolhas',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Calculos Trabalhistas', 'Calculos Trabalhistas'), ('Assistencia Tecnica em Pericia', 'Assistencia Tecnica em Pericia'), ('Engenharia de Seguran\xe7a de Trabalho', 'Engenharia de Seguran\xe7a de Trabalho'), ('Auditoria Trabalhista', 'Auditoria Trabalhista')], max_length=110, verbose_name='Servi\xe7os a serem escolhidos: '),
        ),
    ]
